export { default as logo } from "./Soma.png"
export { default as photo1 } from "./shiroman.jpg"
export { default as photo2 } from "./mikola.jpg"
export { default as photo3 } from "./nathan.jpg"
export {default as photo4} from "./shiromani.jpg"